// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission8_Grp1_6.Models;

#nullable disable

namespace Mission8_Grp1_6.Migrations
{
    [DbContext(typeof(TaskContext))]
    partial class TaskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Mission8_Grp1_6.Models.Task", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quadrant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskID");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskID = 1,
                            Category = "Home",
                            Completed = false,
                            Quadrant = 1,
                            TaskName = "Task 1 Name"
                        },
                        new
                        {
                            TaskID = 2,
                            Category = "School",
                            Completed = false,
                            Quadrant = 2,
                            TaskName = "Task 2 Name"
                        },
                        new
                        {
                            TaskID = 3,
                            Category = "Work",
                            Completed = false,
                            Quadrant = 3,
                            TaskName = "Task 3 Name"
                        },
                        new
                        {
                            TaskID = 4,
                            Category = "Church",
                            Completed = false,
                            Quadrant = 4,
                            TaskName = "Task 4 Name"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
